FROM afdaniele/director:latest

COPY snakefood /tmp/snakefood

RUN cd /tmp/snakefood \
  && python setup.py install \
  && rm -rf /tmp/snakefood

# install dependencies
RUN apt update \
  && apt install -y \
    python-six \
  && rm -rf /var/lib/apt/lists/*

# replace system Python with directorPython
# RUN mv /usr/bin/python /usr/bin/_OLD_python \
#   && ln -s /usr/local/bin/directorPython /usr/bin/python

# set analysis env ID
ENV ENV_ID="director"
