FROM ripl/director:latest

# install dependencies
RUN apt update \
  && apt install -y \
    git \
    graphviz \
    graphviz-dev \
    python3-pip \
  && rm -rf /var/lib/apt/lists/*

# install devel tools
RUN pip3 install \
  SDGraph
